# Generated by Django 5.0.4 on 2024-04-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangesrate',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
