# Generated by Django 5.0.4 on 2024-04-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_exchangesrate_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangesrate',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
