# Generated by Django 5.0.4 on 2024-04-15 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_exchangesrate_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangesrate',
            name='to_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_currency', to='financial.currency'),
        ),
    ]
