# Generated by Django 5.0.4 on 2024-04-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_alter_exchangesrate_to_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangesrate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
